version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: maker_user
      POSTGRES_PASSWORD: maker_password
      POSTGRES_DB: maker_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: