import { CreatePrinterCatalogDto } from './dto/create-printer-catalog.dto.js';

/**
 * FUENTE ÚNICA del catálogo de impresoras predefinido (~29 modelos con su ficha
 * técnica completa: volumen, boquilla, consumo, precio orientativo EUR, enlace
 * oficial, descripción y specs térmicas/velocidad/nº de extrusores).
 *
 * La consumen:
 *  - el endpoint admin `POST /printer-catalog/seed-defaults` (upsert por marca+modelo),
 *  - la migración de backfill de specs (`AddPrinterCatalogSpecs`).
 * El front ya NO define estos datos: los carga vía API (se eliminó su duplicado).
 * La imagen no se guarda: el front la resuelve por marca+modelo (`resolvePrinterImage`).
 *
 * Specs (`extruderMaxTemp`/`bedMaxTemp`/`maxSpeed`/`extruderCount`) tomadas de
 * fuentes oficiales; cuando un dato no es fiable se deja sin poner (lo completa
 * el admin), igual que se hace con el volumen. Precios orientativos y volátiles.
 */
export const DEFAULT_PRINTER_CATALOG: CreatePrinterCatalogDto[] = [
  // ── Anycubic ──────────────────────────────────────────────
  { brand: 'Anycubic', model: 'Kobra S1', type: 'FDM', buildVolumeX: 250, buildVolumeY: 250, buildVolumeZ: 250, nozzleDiameter: 0.4, powerConsumption: 1500, referencePrice: 449, purchaseUrl: 'https://store.anycubic.com/products/kobra-s1', extruderMaxTemp: 320, bedMaxTemp: 120, maxSpeed: 600, extruderCount: 1, description: 'Impresora FDM CoreXY cerrada (250×250×250 mm) con hotend hasta 320 °C, cama a 120 °C, hasta 600 mm/s y multicolor opcional con el módulo ACE Pro.' },
  { brand: 'Anycubic', model: 'Kobra S1 Max', type: 'FDM', buildVolumeX: 350, buildVolumeY: 350, buildVolumeZ: 350, nozzleDiameter: 0.4, powerConsumption: 2200, referencePrice: 899, purchaseUrl: 'https://store.anycubic.com/products/kobra-s1-max', extruderMaxTemp: 350, maxSpeed: 600, extruderCount: 1, description: 'Versión de gran formato (350×350×350 mm) de la Kobra S1: FDM CoreXY cerrada con cámara calefactada, hotend de 350 °C y multicolor de hasta 16 colores con ACE 2 Pro.' },
  { brand: 'Anycubic', model: 'Kobra X1', type: 'FDM', buildVolumeX: 260, buildVolumeY: 260, buildVolumeZ: 260, nozzleDiameter: 0.4, extruderCount: 1, description: 'Impresora FDM de sobremesa multicolor (4 colores nativos), volumen 260×260×260 mm. Verifica el modelo: el producto oficial más cercano es la Anycubic Kobra X.' },

  // ── Bambu Lab ─────────────────────────────────────────────
  { brand: 'Bambu Lab', model: 'A1', type: 'FDM', buildVolumeX: 256, buildVolumeY: 256, buildVolumeZ: 256, nozzleDiameter: 0.4, powerConsumption: 1300, referencePrice: 319, purchaseUrl: 'https://bambulab.com/en/a1', extruderMaxTemp: 300, bedMaxTemp: 100, maxSpeed: 500, extruderCount: 1, description: 'Impresora FDM de cama móvil (bed-slinger) con AMS Lite para multicolor, calibración automática y cambio rápido de boquilla.' },
  { brand: 'Bambu Lab', model: 'A1 mini', type: 'FDM', buildVolumeX: 180, buildVolumeY: 180, buildVolumeZ: 180, nozzleDiameter: 0.4, powerConsumption: 150, referencePrice: 199, purchaseUrl: 'https://bambulab.com/en/a1-mini', extruderMaxTemp: 300, bedMaxTemp: 80, maxSpeed: 500, extruderCount: 1, description: 'Impresora FDM compacta de cama móvil (180 mm) compatible con AMS Lite multicolor y de muy bajo consumo (PSU de 150 W).' },
  { brand: 'Bambu Lab', model: 'A2L', type: 'FDM', buildVolumeX: 330, buildVolumeY: 320, buildVolumeZ: 325, nozzleDiameter: 0.4, powerConsumption: 1000, referencePrice: 379, purchaseUrl: 'https://bambulab.com/en/a2l', extruderMaxTemp: 300, bedMaxTemp: 100, maxSpeed: 500, extruderCount: 1, description: 'Impresora FDM de gran formato y marco abierto de la serie A, con módulo de corte opcional y compatible con AMS Lite multicolor.' },
  { brand: 'Bambu Lab', model: 'H2C', type: 'FDM', buildVolumeX: 305, buildVolumeY: 320, buildVolumeZ: 325, nozzleDiameter: 0.4, referencePrice: 2249, purchaseUrl: 'https://bambulab.com/en-us/h2c', extruderMaxTemp: 350, bedMaxTemp: 120, maxSpeed: 1000, extruderCount: 1, description: 'FDM CoreXY cerrada de gama alta con sistema Vortek de cambio de boquillas (hasta 7 materiales sin purga) y cámara calefactada.' },
  { brand: 'Bambu Lab', model: 'H2D', type: 'FDM', buildVolumeX: 325, buildVolumeY: 320, buildVolumeZ: 325, nozzleDiameter: 0.4, powerConsumption: 2200, referencePrice: 1899, purchaseUrl: 'https://bambulab.com/en/h2d', extruderMaxTemp: 350, bedMaxTemp: 120, maxSpeed: 1000, extruderCount: 2, description: 'FDM CoreXY cerrada de gran formato con doble boquilla, cámara calefactada a 65 °C y módulo láser/corte opcional.' },
  { brand: 'Bambu Lab', model: 'H2S', type: 'FDM', buildVolumeX: 340, buildVolumeY: 320, buildVolumeZ: 340, nozzleDiameter: 0.4, powerConsumption: 2050, referencePrice: 1249, purchaseUrl: 'https://bambulab.com/en-us/h2s', extruderMaxTemp: 350, bedMaxTemp: 120, maxSpeed: 1000, extruderCount: 1, description: 'FDM CoreXY cerrada de gran formato y boquilla única, con cámara calefactada y monitorización por IA (23 sensores, 3 cámaras).' },
  { brand: 'Bambu Lab', model: 'P1S', type: 'FDM', buildVolumeX: 256, buildVolumeY: 256, buildVolumeZ: 256, nozzleDiameter: 0.4, powerConsumption: 1000, referencePrice: 599, purchaseUrl: 'https://us.store.bambulab.com/products/p1s', extruderMaxTemp: 300, bedMaxTemp: 100, maxSpeed: 500, extruderCount: 1, description: 'Impresora FDM CoreXY con cámara cerrada, hotend de 300 °C y compatibilidad con AMS para multicolor.' },
  { brand: 'Bambu Lab', model: 'P2S', type: 'FDM', buildVolumeX: 256, buildVolumeY: 256, buildVolumeZ: 256, nozzleDiameter: 0.4, powerConsumption: 1200, referencePrice: 523, purchaseUrl: 'https://bambulab.com/en-us/p2s', extruderMaxTemp: 300, bedMaxTemp: 100, maxSpeed: 500, extruderCount: 1, description: 'FDM CoreXY cerrada, sucesora de la P1S, con extrusor servo PMSM y compatibilidad AMS multicolor.' },
  { brand: 'Bambu Lab', model: 'X1C', type: 'FDM', buildVolumeX: 256, buildVolumeY: 256, buildVolumeZ: 256, nozzleDiameter: 0.4, powerConsumption: 1000, referencePrice: 1199, purchaseUrl: 'https://bambulab.com/en/x1', extruderMaxTemp: 300, bedMaxTemp: 110, maxSpeed: 500, extruderCount: 1, description: 'FDM CoreXY cerrada tope de gama con hotend de 300 °C, LiDAR para calibración y AMS para multicolor.' },

  // ── Creality ──────────────────────────────────────────────
  { brand: 'Creality', model: 'Ender 3', type: 'FDM', buildVolumeX: 220, buildVolumeY: 220, buildVolumeZ: 250, nozzleDiameter: 0.4, powerConsumption: 360, referencePrice: 189, purchaseUrl: 'https://www.creality.com/products/ender-3-3d-printer', extruderMaxTemp: 250, extruderCount: 1, description: 'Impresora FDM cartesiana (i3) clásica de 220×220×250 mm con extrusor Bowden y hotend hasta 250 °C, el kit económico que popularizó la impresión 3D.' },
  { brand: 'Creality', model: 'K2', type: 'FDM', buildVolumeX: 260, buildVolumeY: 260, buildVolumeZ: 260, nozzleDiameter: 0.4, referencePrice: 549, purchaseUrl: 'https://www.creality.com/products/k2-series-3d-printer', extruderMaxTemp: 300, extruderCount: 1, description: 'Serie K2: FDM CoreXY de 260×260×260 mm con hotend de 300 °C y multicolor por CFS.' },
  { brand: 'Creality', model: 'Spark X7', type: 'FDM', buildVolumeX: 260, buildVolumeY: 260, buildVolumeZ: 255, nozzleDiameter: 0.4, powerConsumption: 700, referencePrice: 399, purchaseUrl: 'https://www.creality.com/products/sparkx-i7', maxSpeed: 500, extruderCount: 1, description: 'FDM cartesiana (nombre oficial SPARKX i7) de 260×260×255 mm, hasta 500 mm/s, multicolor de 4 colores por CFS Lite y cámara con IA anti-fallos.' },

  // ── Elegoo ────────────────────────────────────────────────
  { brand: 'Elegoo', model: 'Centauri Carbon', type: 'FDM', buildVolumeX: 256, buildVolumeY: 256, buildVolumeZ: 256, nozzleDiameter: 0.4, powerConsumption: 1100, referencePrice: 299, purchaseUrl: 'https://eu.elegoo.com/en-es/products/centauri-carbon', extruderMaxTemp: 320, maxSpeed: 500, extruderCount: 1, description: 'FDM CoreXY cerrada (256×256×256 mm) hasta 500 mm/s, con boquilla de acero endurecido a 320 °C para filamentos con fibra de carbono.' },
  { brand: 'Elegoo', model: 'Centauri Carbon 2', type: 'FDM', buildVolumeX: 256, buildVolumeY: 256, buildVolumeZ: 256, nozzleDiameter: 0.4, referencePrice: 329, purchaseUrl: 'https://eu.elegoo.com/en-es/products/centauri-carbon-2', extruderMaxTemp: 350, maxSpeed: 500, extruderCount: 1, description: 'Evolución multicolor y multimaterial de la Centauri Carbon: CoreXY cerrada (256 mm), hasta 500 mm/s y boquilla endurecida de 350 °C.' },
  { brand: 'Elegoo', model: 'OrangeStorm Giga', type: 'FDM', buildVolumeX: 800, buildVolumeY: 800, buildVolumeZ: 1000, nozzleDiameter: 0.4, powerConsumption: 1800, referencePrice: 2399, purchaseUrl: 'https://eu.elegoo.com/en-es/products/orangestorm-giga', extruderMaxTemp: 300, extruderCount: 1, description: 'FDM de gran formato (800×800×1000 mm) con cama dividida en cuatro plataformas PEI y boquilla de latón hasta 300 °C, para piezas de gran tamaño.' },

  // ── Flashforge ────────────────────────────────────────────
  { brand: 'Flashforge', model: 'AD5X', type: 'FDM', buildVolumeX: 220, buildVolumeY: 220, buildVolumeZ: 220, nozzleDiameter: 0.4, powerConsumption: 650, referencePrice: 379, purchaseUrl: 'https://www.flashforge.com/products/flashforge-ad5x-3d-printer', extruderMaxTemp: 300, extruderCount: 1, description: 'FDM CoreXY multicolor de hasta 4 filamentos (220×220×220 mm) derivada de la Adventurer 5M, con extrusor directo hasta 300 °C y cambio rápido de boquilla.' },
  { brand: 'Flashforge', model: 'Creator 5', type: 'FDM', buildVolumeX: 256, buildVolumeY: 256, buildVolumeZ: 256, nozzleDiameter: 0.4, powerConsumption: 700, referencePrice: 679, purchaseUrl: 'https://www.flashforge.com/products/flashforge-creator-5', extruderCount: 4, description: 'FDM CoreXY con cambiador de 4 cabezales independientes (multimaterial sin purga) y volumen de 256×256×256 mm, versión de bastidor abierto.' },
  { brand: 'Flashforge', model: 'Creator 5 Pro', type: 'FDM', buildVolumeX: 256, buildVolumeY: 256, buildVolumeZ: 256, nozzleDiameter: 0.4, powerConsumption: 1200, referencePrice: 829, purchaseUrl: 'https://www.flashforge.com/products/flashforge-creator-5-pro', extruderCount: 4, description: 'Versión Pro cerrada con cámara calefactada hasta 65 °C y filtración HEPA: FDM CoreXY con 4 cabezales intercambiables (256 mm) para ABS/ASA.' },

  // ── Prusa ─────────────────────────────────────────────────
  { brand: 'Prusa', model: 'Core One', type: 'FDM', buildVolumeX: 250, buildVolumeY: 220, buildVolumeZ: 270, nozzleDiameter: 0.4, powerConsumption: 110, referencePrice: 1349, purchaseUrl: 'https://www.prusa3d.com/product/prusa-core-one/', extruderCount: 1, description: 'FDM CoreXY totalmente cerrada con cámara calefactada activa hasta 55 °C, extrusor directo y estructura tipo exoesqueleto para alta velocidad.' },
  { brand: 'Prusa', model: 'Core One L', type: 'FDM', buildVolumeX: 300, buildVolumeY: 300, buildVolumeZ: 330, nozzleDiameter: 0.4, powerConsumption: 215, referencePrice: 1849, purchaseUrl: 'https://www.prusa3d.com/product/prusa-core-one-l-2/', extruderCount: 1, description: 'Versión de gran formato de la Core One: CoreXY cerrada con 30 L (300×300×330 mm), cama de aluminio por convección y cámara activa hasta 60 °C.' },
  { brand: 'Prusa', model: 'MK3', type: 'FDM', buildVolumeX: 250, buildVolumeY: 210, buildVolumeZ: 210, nozzleDiameter: 0.4, powerConsumption: 120, purchaseUrl: 'https://www.prusa3d.com/category/original-prusa-i3-mk3s/', extruderCount: 1, description: 'Original Prusa i3 MK3S+, FDM cartesiana con extrusor directo Bondtech y láminas de acero PEI extraíbles (descatalogada salvo edición aniversario).' },
  { brand: 'Prusa', model: 'MK3.5', type: 'FDM', buildVolumeX: 250, buildVolumeY: 210, buildVolumeZ: 210, nozzleDiameter: 0.4, powerConsumption: 120, purchaseUrl: 'https://www.prusa3d.com/product/original-prusa-mk3-5s-3d-printer/', extruderCount: 1, description: 'Modernización del MK3S+ (electrónica xBuddy de 32 bits, Input Shaper y Wi-Fi/LAN) conservando chasis y volumen; se vende como kit.' },
  { brand: 'Prusa', model: 'MK4S', type: 'FDM', buildVolumeX: 250, buildVolumeY: 210, buildVolumeZ: 220, nozzleDiameter: 0.4, powerConsumption: 120, referencePrice: 1099, purchaseUrl: 'https://www.prusa3d.com/product/original-prusa-mk4s-3d-printer/', extruderCount: 1, description: 'Buque insignia FDM cartesiano (i3) con extrusor directo Nextruder, autonivelación por célula de carga y boquilla de alto caudal CHT.' },
  { brand: 'Prusa', model: 'Mini+', type: 'FDM', buildVolumeX: 180, buildVolumeY: 180, buildVolumeZ: 180, nozzleDiameter: 0.4, powerConsumption: 160, referencePrice: 509, purchaseUrl: 'https://www.prusa3d.com/category/original-prusa-mini/', extruderCount: 1, description: 'Impresora FDM cartesiana compacta (180 mm) con nivelación automática, hotend íntegramente metálico y conectividad de red; se entrega semimontada.' },
  { brand: 'Prusa', model: 'XL', type: 'FDM', buildVolumeX: 360, buildVolumeY: 360, buildVolumeZ: 360, nozzleDiameter: 0.4, powerConsumption: 235, referencePrice: 2299, purchaseUrl: 'https://www.prusa3d.com/product/original-prusa-xl-assembled-single-toolhead-3d-printer/', extruderCount: 1, description: 'FDM CoreXY de gran formato (360 mm) con extrusor Nextruder y cama segmentada en 16 zonas independientes; ampliable hasta 5 cabezales.' },

  // ── Snapmaker ─────────────────────────────────────────────
  { brand: 'Snapmaker', model: 'U1', type: 'FDM', buildVolumeX: 270, buildVolumeY: 270, buildVolumeZ: 270, nozzleDiameter: 0.4, powerConsumption: 1150, referencePrice: 899, purchaseUrl: 'https://eu.snapmaker.com/products/snapmaker-u1-3d-printer', extruderCount: 4, description: 'FDM CoreXY con sistema SnapSwap de 4 cabezales (cambio en ~5 s) y volumen de 270×270×270 mm, para multicolor y multimaterial con bajo desperdicio.' },
];
